name = "space_game"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
sqlight = ">= 1.0.2 and < 2.0.0"
cake = ">= 2.1.3 and < 3.0.0"
cake_sqlight = ">= 1.1.2 and < 2.0.0"
logging = ">= 1.3.0 and < 2.0.0"
glenvy = ">= 2.0.1 and < 3.0.0"
stratus = { git = "https://github.com/arconyx/stratus.git", ref = "a006758" }
gleam_hackney = ">= 1.3.1 and < 2.0.0"
gleam_http = ">= 4.1.1 and < 5.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_otp = ">= 1.1.0 and < 2.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
gramps = ">= 6.0.0 and < 7.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
